
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.2.31:3306/spvi?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root

    druid:
      initial-size: 5
      min-idle: 1
      max-active: 20
      query-timeout: 6000
      remove-abandoned: false
      async-init: true
      time-between-connect-error-millis: 3000


      log-abandoned: false
      transaction-query-timeout: 6000
      remove-abandoned-timeout: 1800
      filters: wall,stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=2000
      stat-view-servlet:
        login-username: mi
        login-password: mi
        url-pattern: /druid/*
        reset-enable: false
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      connection-error-retry-attempts: 3
      break-after-acquire-failure: false
      validation-query: select 1 from dual
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

mybatis:
  type-aliases-package: com.dongguabai.dongguabaitask.server.persistence.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mapper:
  mappers: io.github.dongguabai.server.persistence.GenericMapper
  not-empty: true
  identity: MYSQL

logging:
  level:
    java.sql: debug
    com.apache.ibatis: debug
    com.dongguabai.dongguabaitask.server.persistence.repository: debug
server:
  port: 9090
